//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AryarajsinhHarma_0516_Models.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wallet()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int Wallet_id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> DebitAmount { get; set; }
        public Nullable<int> creditAmout { get; set; }
        public Nullable<int> totalAmount { get; set; }
        public Nullable<System.DateTime> DebitDate { get; set; }
        public Nullable<int> RemainingChance { get; set; }
    
        public virtual Register Register { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
